// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cloud_logic': 'enable',
    'aws_cloud_logic_custom': [{"id":"wv4drsoyo6","name":"GetIncidentReports","description":"Returns a list of Incident Reports","endpoint":"https://wv4drsoyo6.execute-api.us-east-1.amazonaws.com/alpha","region":"us-east-1","paths":["/"]},{"id":"b7xopcbggh","name":"SubmitIncidentReport","description":"Allows user to create an Incident Report or to update an existing one.","endpoint":"https://b7xopcbggh.execute-api.us-east-1.amazonaws.com/alpha","region":"us-east-1","paths":["/"]},{"id":"548ymwfm2i","name":"MatchSearch","description":"Returns a list of Matches based on location or other information","endpoint":"https://548ymwfm2i.execute-api.us-east-1.amazonaws.com/alpha","region":"us-east-1","paths":["/"]},{"id":"vu83zwopu5","name":"GetMatchDetail","description":"Returns a description of a match given the Match ID","endpoint":"https://vu83zwopu5.execute-api.us-east-1.amazonaws.com/alpha","region":"us-east-1","paths":["/"]},{"id":"hrr4vu8a69","name":"GetSquaddingList","description":"Given a passed in MatchID, returns the squadding list.","endpoint":"https://hrr4vu8a69.execute-api.us-east-1.amazonaws.com/alpha","region":"us-east-1","paths":["/"]}],
    'aws_cognito_identity_pool_id': 'us-east-1:ecdb1323-5308-445f-845e-55871ebf14e2',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'orionmobileapp-hosting-mobilehub-1376837905',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd30i2h4a1keorx.cloudfront.net',
    'aws_mobile_analytics_app_id': '8f3de4fd492842cda67d2df82d97876f',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '6a67636f-223d-11e8-ad53-35ba40123370',
    'aws_project_name': 'orionMobileApp',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'orionmobileapp-mobilehub-1376837905',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-1_EOdAipVdq',
    'aws_user_pools_mfa_type': 'ON',
    'aws_user_pools_web_client_id': '6bim5j26a7cjsl5omabar19vi6',
}

export default awsmobile;
